@startuml
package "cinema" {
class "Movie" as Movie {
    .. Attributes ..
    duration
    title
    .. Methods ..
    __init__() [line: 11]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\cinema\cinema.py
    .. Line Number ..
    10
}
}
package "cinema" {
class "CinemaHall" as CinemaHall {
    .. Attributes ..
    capacity
    hall_number
    bookings
    booking
    .. Methods ..
    __init__() [line: 21]
    add_booking() [line: 27]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\cinema\cinema.py
    .. Line Number ..
    16
}
}
package "cinema" {
class "Booking" as Booking {
    .. Attributes ..
    movie
    hall
    customer
    .. Methods ..
    __init__() [line: 36]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\cinema\cinema.py
    .. Line Number ..
    35
}
}
package "cinema" {
class "Customer" as Customer {
    .. Attributes ..
    email
    name
    .. Methods ..
    __init__() [line: 43]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\cinema\cinema.py
    .. Line Number ..
    42
}
}
package "library" {
class "Book" as Book {
    .. Attributes ..
    author
    isbn
    borrowed
    title
    .. Methods ..
    __init__() [line: 2]
    borrow() [line: 8]
    return_book() [line: 14]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\library\book.py
    .. Line Number ..
    1
}
}
package "library" {
class "Library" as Library {
    .. Attributes ..
    books
    members
    .. Methods ..
    __init__() [line: 5]
    add_book() [line: 9]
    add_member() [line: 13]
    find_book() [line: 17]
    find_member() [line: 23]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\library\library.py
    .. Line Number ..
    4
}
}
package "library" {
class "Member" as Member {
    .. Attributes ..
    borrowed_books
    member_id
    name
    .. Methods ..
    __init__() [line: 4]
    borrow_book() [line: 9]
    return_book() [line: 15]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\library\member.py
    .. Line Number ..
    3
}
}
package "zoo" {
class "Animal" as Animal {
    .. Attributes ..
    species
    name
    .. Methods ..
    __init__() [line: 3]
    make_sound() [line: 7]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\zoo\animals.py
    .. Line Number ..
    2
}
}
package "zoo" {
class "Dog" as Dog {
    .. Attributes ..
    breed
    .. Methods ..
    __init__() [line: 12]
    make_sound() [line: 16]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\zoo\animals.py
    .. Line Number ..
    11
}
}
package "zoo" {
class "Owner" as Owner {
    .. Attributes ..
    dog
    name
    .. Methods ..
    __init__() [line: 21]
    walk_dog() [line: 25]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\zoo\animals.py
    .. Line Number ..
    20
}
}
package "zoo.animals" {
class "Cat" as Cat {
    .. Attributes ..
    age
    name
    .. Methods ..
    __init__() [line: 4]
    meow() [line: 8]
    __str__() [line: 11]
    .. File Path ..
    C:\Users\grank\Downloads\wetransfer_test_project_2024-12-03_1619\test_project\zoo\animals\cat.py
    .. Line Number ..
    3
}
}
cinema.CinemaHall ..> Booking : uses
cinema.CinemaHall --> Booking : composed of
library.Library ..> Member : uses
library.Library ..> Book : uses
zoo.Dog <|-- Animal
zoo.animals.Cat <|-- Animal
@enduml
